services:
  login:
    restart: always
    build:
      context: gamel
      dockerfile: Dockerfile
    expose:
      - 7171
    ports:
      - 7171:7171
    command:
      - /bin/sh
      - -c
      - |
        export GAMESERVER_IP=127.0.0.1
        export QUERY_MANAGER_IP=$(getent hosts query-manager | awk '{ print $1 }')
        ./gamel

  game:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.game
    expose:
      - 7172
    ports:
      - 7172:7172
    environment:
      GAME_PATH: /home/game
    # FIXME: use GAME_PATH instead of hardcoded path
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        echo "Co tam sie odjaniepawla"

        export QUERY_MANAGER_IP=$(getent hosts query-manager | awk '{ print $1 }')
        echo $$QUERY_MANAGER_IP

        cp /home/game.tibia ~/.tibia
        sed -i "s/query-manager/$$QUERY_MANAGER_IP/g" ~/.tibia
        cat ~/.tibia

        cd /home/game
        echo "Running game server from '/home/game/bin/game'..."
        rm save/game.pid || echo "Pid does not exist"
        ./bin/game
        echo "kuzwa mac XDD"
  query-manager:
    build:
      context: oracle
      dockerfile: Dockerfile
    restart: :always
    expose:
      - 17778
    command:
      - /bin/sh
      - -c
      - |
        ./oracle
