services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: gamel
      MYSQL_DATABASE: otserv
      MYSQL_USER: otserv
      MYSQL_PASSWORD: otserv
  login:
    restart: always
    build:
      context: gamel
      dockerfile: Dockerfile
    expose:
      - 7171
    ports:
      - 7171:7171
    command:
      - /bin/sh
      - -c
      - |
        cat accounts.db
        export GAMESERVER_IP=127.0.0.1
        ./gamel

  game:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.game
    expose:
      - 7172
    ports:
      - 7172:7172
  query-manager:
    restart: always
    expose:
      - 17778
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.query-manager
    command:
      - /bin/bash
      - -c
      - |
        set -e

        cat <<EOF > config.lua
        -- SQL Settings
        mysqlHost = "mysql"
        mysqlUser = "otserv"
        mysqlPass = "otserv"
        mysqlDatabase = "otserv"

        -- Connection Settings
        ip = "0.0.0.0" -- use 0.0.0.0 to bind all interfaces
        port = 17778

        -- Game Server Settings
        gameIp = "0.0.0.0" -- use 0.0.0.0 to bind all interfaces
        gamePort = 7172
        serverSaveHour = 5
        worldType = 0 -- normal pvp = 0, non-pvp = 1, pvp enforced = 2
        maxPlayers = 1500
        maxPlayersNewbies = 500
        premBuffer = 900
        reservedPremiumNewbies = 250
        EOF
        ./bin/realotsquerymanager
