services:
  login:
    restart: always
    build:
      context: gamel
      dockerfile: Dockerfile
    depends_on:
      - query-manager
    expose:
      - 7171
    ports:
      - 7171:7171
    command:
      - /bin/sh
      - -c
      - |
        export GAMESERVER_IP=127.0.0.1
        export QUERY_MANAGER_IP=$(getent hosts query-manager | awk '{ print $1 }')
        ./gamel

  game:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.game
    depends_on:
      - query-manager
    expose:
      - 7172
    ports:
      - 7172:7172
    environment:
      GAME_PATH: /home/game
  query-manager:
    build:
      context: oracle
      dockerfile: Dockerfile
    restart: :always
    expose:
      - 17778
    command:
      - /bin/sh
      - -c
      - |
        ./oracle
