services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: gamel
      MYSQL_DATABASE: otserv
      MYSQL_USER: otserv
      MYSQL_PASSWORD: otserv
    # healthcheck:
    #   test: CMD-SHELL
    #     mysql -h localhost -u otserv --password=otserv -e "use otserv;"
  game:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.game
    expose:
      - 7172
    environment:
      GAME_PATH: /home/game
    # FIXME: use GAME_PATH instead of hardcoded path
    command:
      - /bin/bash
      - -c
      - |
        rm ~/.tibia
        cat <<EOF > ~/.tibia
        # Tibia - Graphical Multi-User-Dungeon
        # .tibia: Konfigurationsdatei (Game-Server)

        # Verzeichnisse
        BINPATH     = "/home/game/bin"
        MAPPATH     = "/home/game/map"
        ORIGMAPPATH = "/home/game/origmap"
        DATAPATH    = "/home/game/dat"
        USERPATH    = "/home/game/usr"
        LOGPATH     = "/home/game/log"
        SAVEPATH    = "/home/game/save"
        MONSTERPATH = "/home/game/mon"
        NPCPATH     = "/home/game/npc"

        # SharedMemories
        SHM = 10011

        # DebugLevel
        DebugLevel = 2

        # Server-Takt
        Beat = 50

        # QueryManager
        QueryManager = {("query-manager",17778,"nXE?/>j`"),("query-manager",17778,"nXE?/>j`"),("query-manager",17778,"nXE?/>j`"),("query-manager",17778,"nXE?/>j`")}

        # Weltstatus
        World = "Zanera"
        State = public
        EOF
        echo "Running game server from '/home/game/bin/game'..."
        rm /home/game/save/game.pid || echo "No PID file found"
        chmod +x /home/game/bin/game
        /home/game/bin/game
  query-manager:
    restart: always
    expose:
      - 17778
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.query-manager
    command:
      - /bin/bash
      - -c
      - |
        set -e
        # mysql -h mysql -u otserv --password=otserv -D otserv -e 'source /data.sql'

        cat <<EOF > config.lua
        -- SQL Settings
        mysqlHost = "mysql"
        mysqlUser = "otserv"
        mysqlPass = "otserv"
        mysqlDatabase = "otserv"

        -- Connection Settings
        ip = "0.0.0.0" -- use 0.0.0.0 to bind all interfaces
        port = 17778

        -- Game Server Settings
        gameIp = "0.0.0.0" -- use 0.0.0.0 to bind all interfaces
        gamePort = 7172
        serverSaveHour = 5
        worldType = 0 -- normal pvp = 0, non-pvp = 1, pvp enforced = 2
        maxPlayers = 1500
        maxPlayersNewbies = 500
        premBuffer = 900
        reservedPremiumNewbies = 250
        EOF
        ./bin/realotsquerymanager
